
server.port=8066
spring.profiles.active=linux



start.date.ewaybill=01-04-2018
start.date.values=01-01-2025

api.development.file.location=${APIDEVELOPMENT_PATH:D:/API_Development/software/GST_Production_Latest_Public_key/GSTN_G2B_Prod_public.cer}



#eway end

clientId=18_ASSAM
clientSecret=5526720892
stateCode=18
userNames=assam_18123
password=assam_18123
url=https://dex.ewaybillgst.gov.in/v1.3/Authenticate
pubKey = MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2PkhjvWu+lDEv/ane+uVN44MAZBhWn2Xbr5zEu7h9LpXJXhrwKYhtvWR6YmjAR4AcXDwA3P74Hjc8/jsW92Q5B4ddXJrRbsU3lac1GhjCNma31FlW7Mpjr5eqPNTuImJr1WgDR9iRuCFYt4enRkvfywdnDa++QK6fdjS4/kssJxlEXBtlXKoFuSBGjbf0JA56qHo8yqXoYoqgl9Z7e9X8GZv6soB1JDH9dxMmaqEwsxaonDG+8NdR2RcYeJAnx2s/PBokpbCVPCQiSD5mmYWSZePF7L4mqvYS7ByrIj1cBH8qq6TafTcLkrr/TiZjpAADPwuynQDE120BpFaqIEqlQIDAQAB
encAppKey=PdWVUuJ2wFIlj2jV01tAC/mQYB96sYJ+aYH/F1kaEeOxpiNQi72XFFzoiSNtr42s5p6IIG+WxxI0JcRiUyrWsgkifBVU72iLUr+H6aemO0VbH8ZL7RlNbBatuPpEP+TqxTCL6QtMXCpXalQvGy5TuJWACu93d5MLHAVHM7HUxG0YS8vIr/F8EL+z4eN39D4dM1aUceFFDOpCT+XeEmo2ySgYtFjChFUrOMOD2BkYf4E1Il/BRd98/AQDrasecXa9+U0vpQtgocnpqWRQS2dimve/b7TmO62hJe6HYp/AsNZyaNpdND8L4HyZGPZd6YH9T+YnV/sg/P5YFLStaTdhaA==



file_detail_url=https://dex.ewaybillgst.gov.in/v1.3/api/ewayApi/GetEWBFile?action=FILEDET
file_count_url=https://dex.ewaybillgst.gov.in/v1.3/api/ewayApi/GetEWBFile?action=FILECNT
eway_common_url=https://dex.ewaybillgst.gov.in/v1.3/api/ewayApi/GetEWBFile

spring.application.name=GST Processing Microservice
application.version=1.0.0
application.start-time=${spring.main.banner-mode}


#spring.application.name=ctd
spring.security.user.name=admin
spring.security.user.password=admin

###################
# ==============================
# SERVER
# ==============================
server.tomcat.max-threads=100
server.tomcat.accept-count=50

# ==============================
# HIKARI CONNECTION POOL
# ==============================
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# ==============================
# JPA PERFORMANCE
# ==============================
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.open-in-view=false

# ==============================
# ASYNC TASK EXECUTOR (optional override)
# ==============================
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=100

# ==============================
# LOGGING
# ==============================
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=ERROR
######################

logging.level.root=INFO

# Hide HikariCP logs
logging.level.com.zaxxer.hikari=ERROR

# Hide Apache HttpClient logs
logging.level.org.apache.http=ERROR
logging.level.org.apache.hc=ERROR

# Hide Spring Data Redis auto-scan logs
logging.level.org.springframework.data.redis=ERROR

# Reduce Spring noise
logging.level.org.springframework=INFO

# Reduce Hibernate noise
logging.level.org.hibernate=ERROR
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

# Jasypt Configuration
jasypt.encryptor.algorithm=PBEWithMD5AndDES
jasypt.encryptor.password=mySecretKeys

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false
spring.codec.max-in-memory-size=10MB


#file_detail_url=https://dex.ewaybillgst.gov.in/v1.3/api/ewayApi/GetEWBFile?action=FILEDET
#file_count_url=https://dex.ewaybillgst.gov.in/v1.3/api/ewayApi/GetEWBFile?action=FILECNT

# ================= GST FILE PATHS =================
#app.log.path=${user.home}/logs

























